version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-cg
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-cg
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-cg
    hostname: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=Default
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    ports:
      - 8080:8080

  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - dbdata6:/data/db

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379

  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_DB: cognitia
      POSTGRES_USER: cognitia
      POSTGRES_PASSWORD: cognitia123
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dbdata6:
  postgres_data: